= uthreads - user mode threads

This folder contains of a set of examples used in the Concurrent Programming course, namely the _uthreads_ user mode cooperative multi-threading system.
See the link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/uthreads.adoc[uthreads - User Mode Cooperative Threads] for a more detailed description of this system.
See link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/uthreads.adoc#development-and-execution-environment[Development and execution environment] for information on how to explore, build, and run the example programs.

* link:first[first] - illustrates how to build a tiny program composed by an assembly source file and a C source file, with the main goal of illustrating the interface between both.
* link:uthreads-0-minimal[uthreads-0-minimal] - contains the first _uthreads_ version, without any control synchronization and with just a `ut_yield` function that keeps the calling thread in the _ready_ (or _running_) state.
* link:uthreads-1-join[uthreads-1-join] - contains the second _threads_ version, adding control synchronization by allow threads to wait for other threads to complete via a `ut_join` function.
* link:uthreads-2-sockets[uthreads-2-sockets] - contains the third and last _uthreads_ version, adding support for socket I/O. It includes a small echo TCP server based on it.

# Exercises about _uthreads_

To develop and run _uthreads_ with Visual Studio Code in a container, use the following procedure:

* Make sure Docker Desktop is installed.
* Open Visual Studio Code in the `native` folder.
* Make sure the `Dev Containers` extension is installed.
* On the bottom left corner, click the icon and select `Open in container`.
* Open a terminal in Visual Studio Code and run
** `uname` - Should print `Linux`, meaning that it is a shell running on Linux and not on the host OS.
** `gcc --version` - Should print something like `gcc (Debian 12.2.0-14) 12.2.0`, meaning that the C development tools are available.
* To reopen Visual Studio Code on the host OS, use the bottom left corner and select `Reopen Folder Locally`.

## `uthreads-0-minimal` folder

* When does a call to `ut_run` returns?
.. Always before any other thread runs.
.. After `context_switch` is called once on each thread.
.. After the main thread calls `ut_yield`.
.. When there aren't anymore threads in the ready state. 

* What does `ut_init` does?
.. Allocate the stack for the main thread.
.. Creates the main thread.
.. Initializes the ready queue.
.. Does a context_switch.

* When is the memory for the thread descriptor de-allocated?
.. Never.
.. When `ut_free` is called.
.. When `context_switch_and_free` is called.
.. when `ut_run` returns.

* The location of each thread stack and descriptor is
.. Unrelated.
.. The descriptor is located at the top of the memory area reserved for the stack.
.. The descriptor is located at the bottom of the memory area reserved for the stack.
.. The descriptor is always located at the _top of the stack_.

* On the `context_switch_and_free`, why is the call to the `free` function done _after_ the instruction `movq (%rsi), %rsp`?

* Change the source code so that
** The `ut_create` function receives a thread name.
** Every `context_switch`` writes in the standard output the names of the two threads involved in that switch.

## `uthreads-1-join` folder

* Why did the `context_switch_and_free` function needed to be changed for this new _uthreads_ version?

* Why is `schedule` sometimes called inside the function `ut_join`? When does the `schedule` call return?

* What happens if a thread `t1` joins with a thread `t2` and the `t2` thread also joins with the `t1` thread?

